version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: drone_user
      POSTGRES_PASSWORD: drone_pass
      POSTGRES_DB: drone_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
  orders-service:
    build: ./services/orders-service
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: drone_user
      DB_PASS: drone_pass
      DB_NAME: drone_db
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data:
